server:
  port: 2001
spring:
  datasource:
    url: jdbc:mysql://localhost:3304/PAY?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false